Бездольный Н.А.
ipetropolsky/xslt-intro pull request #4
Opened 2018-01-28 10:59 UTC by gooverdian

2018-02-05 09:15 UTC, ipetropolsky requested changes

2018-02-05 09:15 UTC, ipetropolsky commented on homework/output/placeholder.txt
> +This will ensure presence of a directory.
Можно положить файл `.gitkeep`, см. https://github.com/ipetropolsky/xslt-intro/tree/46493c506dee1c6be80ceeb838a91b7a5036212b/homework

2018-02-05 09:15 UTC, ipetropolsky commented on homework/output/result1.xml
> +<root response="True">
1) Зачем `response="True"`?
2) Если у ответов разных типов такой общий корневой элемент (`root`), это скорее всего какой-то фреймворк + лень разработчика. Одинаковый элемент имеет смысл, если он как-то описывает формат, содержание или тип документа (как `<html>`, `<svg>` или `<udata>` в UMI).

2018-02-05 09:15 UTC, ipetropolsky commented on homework/output/result1.xml
> +    <movie year="2014" runtime="169 min" metascore="74" imdbRating="8.6" imdbVotes="1112625" imdbID="tt0816692" type="movie">
1) Как получить число минут для сравнения или вывода в шаблоне?
2) `imdb*` так и просятся в отдельный элемент. И что если добавятся данные другой базы или рейтинга?

2018-02-05 09:15 UTC, ipetropolsky commented on homework/output/result1.xml
> +		<release>07 Nov 2014</release>
Как отсортировать по такой дате набор фильмов? Или вывести «7 ноября».

2018-02-05 09:15 UTC, ipetropolsky commented on homework/output/result1.xml
> +		<!-- Релизов тоже может быть несколько, в кино, на DVD, в Китае -->
👍

2018-02-05 09:15 UTC, ipetropolsky commented on homework/output/result1.xml
> +            <actor>John Lithgow</actor>
Хорошая идея объединить участников, но именно такой формат вряд ли будет юзабелен.
Во-первых, это очень похожие сущности, но названы по-разному, соответственно клиентскому коду нужно будет применять одну и ту же обработку для разных элементов, а это всегда боль.
Во-вторых, не хватает ID, ведь имена могут повторяться, и полезно было бы иметь ссылку на профиль (см. идеологию [HATEOAS](https://ru.wikipedia.org/wiki/HATEOAS)).
В-третьих, представь то же самое в JSON (API часто работает в обоих форматах), как это могло бы выглядеть?

2018-02-05 09:15 UTC, ipetropolsky commented on homework/output/result1.xml
> +        <country>Iceland</country>
Всё-таки лучше упаковывать списки в отдельные элементы, например `country` в `countries`.
Опять же, представь то же самое в JSON, в текущем формате автоматически не замапишь одно в другое.

2018-02-05 09:15 UTC, ipetropolsky commented on homework/output/result1.xml
> +			Won 1 Oscar. Another 43 wins ' 143 nominations.
👍

2018-02-05 09:15 UTC, ipetropolsky commented on homework/output/result1.xml
> +		</poster>
Что-то с отступами.

2018-02-05 09:15 UTC, ipetropolsky commented on homework/output/task1_errors.txt
> +<root response="False">
Нуу… Идея понятна, но это же тоже ответ )

2018-02-05 09:15 UTC, ipetropolsky commented on homework/output/task1_errors.txt
> +	<error>Invalid API key!</error>
Это будет 400, ошибка в запросе.

2018-02-05 09:15 UTC, ipetropolsky commented on homework/output/task1_errors.txt
> +	<error>Switch to next API version for this request</error>
Это про протокол: https://developer.mozilla.org/ru/docs/Web/HTTP/Status/426

2018-02-05 09:15 UTC, ipetropolsky commented on homework/output/task1_errors.txt
> +	<error>Unsuccessful coffee making</error>
☕️

2018-02-05 09:15 UTC, ipetropolsky commented on homework/output/task1_errors.txt
> +	<error>API Key rate limit reached</error>
👍

2018-02-05 09:15 UTC, ipetropolsky commented on homework/output/task1_errors.txt
> +так что просто передаем название статускода в тексте
Обычно ошибки 5xx — это внутренняя кухня сервера, которую и не надо выставлять наружу, так что просто отвечаем `503 Service Unavailable`, если что-то упало, но код способен это понять и ответить, либо `500 Internal Server Error`, если упал сам отвечающий код, то есть первая линия бэкендов.

2018-02-05 09:15 UTC, ipetropolsky commented on homework/output/task1_errors.txt
> +	<error>There is no method details on author</error>
Что тут имелось в виду?

2018-02-05 09:15 UTC, ipetropolsky commented on homework/task2.xsl
> +	    <category id="{@id}">
Табы вместе с пробелами — хуже не придумаешь ) Лучше всегда использовать пробелы.

2018-02-05 09:15 UTC, ipetropolsky commented on homework/README.md
> +xsltproc --output output/result2.xml task2.xsl catalog.xml
```
Parsing stylesheet task2.xsl took 0 ms
Parsing document catalog.xml took 113 ms
Applying stylesheet took 6 ms
Saving result took 0 ms
```

2018-02-05 09:15 UTC, ipetropolsky commented on homework/task3.xsl
> +	<xsl:output indent="yes"/>
```xsl
<param name="&#x422;&#x438;&#x43F;">Степлер</param>
```
Потому что `output` без `encoding`.

2018-02-05 09:15 UTC, ipetropolsky commented on homework/README.md
> +xsltproc --param category 1177528 --output output/result3.xml task3.xsl catalog.xml
```
Parsing stylesheet task3.xsl took 0 ms
Parsing document catalog.xml took 116 ms
Applying stylesheet took 34 ms
Saving result took 9 ms
```

2018-02-05 09:15 UTC, ipetropolsky commented on homework/README.md
> +xsltproc --param category 1177528 --output output/result4.html task4.xsl catalog.xml
```
Parsing stylesheet task4.xsl took 0 ms
Parsing document catalog.xml took 120 ms
Applying stylesheet took 83 ms
Saving result took 21 ms
```

2018-02-05 09:15 UTC, ipetropolsky commented on homework/README.md
> +xsltproc --output output/result_offer_tree.xml task_offer_tree.xsl catalog.xml
```
Parsing stylesheet task_offer_tree.xsl took 0 ms
Parsing document catalog.xml took 119 ms
Applying stylesheet took 247 ms
Saving result took 39 ms
```

2018-02-05 09:15 UTC, ipetropolsky commented on homework/README.md
> +xsltproc --output output/result_group_by.xml task_group_by.xml catalog.xml
`task_group_by.xml` → `task_group_by.xsl`
```
Parsing stylesheet task_group_by.xsl took 0 ms
Parsing document catalog.xml took 116 ms
Applying stylesheet took 110 ms
Saving result took 40 ms
```

2018-02-05 09:15 UTC, ipetropolsky commented on homework/task4.xsl
> +	<xsl:import href="task4_salePrice.xsl"/>
Уже подключили выше.

2018-02-05 09:15 UTC, ipetropolsky commented on homework/task3.xsl
> +		<xsl:copy-of select="current()"/>
Тут можно `.`, `current()` для ссылки на контекст шаблона в сложном xpath.

2018-02-05 09:15 UTC, ipetropolsky commented on homework/task4.xsl
> +	<xsl:output indent="yes"/>
Лучше указать всё в одном `output`.

2018-02-05 09:15 UTC, ipetropolsky commented on homework/task4.xsl
> +	<xsl:import href="task4_saleOffer.xsl"/>
Здорово, что всё разделил. Возможно имеет смысл `salePrice` положить в `saleOffer`, чтобы одним подключением добавлять все стили для распродаж.

2018-02-05 09:15 UTC, ipetropolsky commented on homework/task4.xsl
> +		<xsl:text disable-output-escaping="yes">&lt;!DOCTYPE html&gt;</xsl:text>
`disable-output-escaping` — опасная штука, лучше в `xsl:output` указать:
```xml
doctype-system="about:legacy-compat"
```

2018-02-05 09:15 UTC, ipetropolsky commented on homework/task4.xsl
> +				<title><xsl:text>Каталог</xsl:text></title>
`xsl:text` в таких простых случаях не нужен.

2018-02-05 09:15 UTC, ipetropolsky commented on homework/task4.xsl
> +					<h2><xsl:value-of select="shop/categories/category[@id = $category]" /></h2>
Ok, но лучше применить к этой категории шаблон с `mode="page-title"`, который будет знать, что вывести в заголовок (может просто текст, а может добавит ссылку или ещё что).

2018-02-05 09:15 UTC, ipetropolsky commented on homework/task4.xsl
> +					<xsl:apply-templates select="shop/offers"/>
Ну тут уж можно было и заинлайнить шаблон для `offers`. Не принципиально.

2018-02-05 09:15 UTC, ipetropolsky commented on homework/task4_dividableOffer.xsl
> +		<div class="col-3">
На узком экране выглядит интересно )

2018-02-05 09:15 UTC, ipetropolsky commented on homework/task4.xsl
> +		<xsl:apply-imports />
`apply-imports` нужен, когда и в этом шаблоне что-то рисуется, и подключённые тоже надо отрисовать. А тут он без надобности, проще убрать из этого файла `offerWrapper `.

То же самое про `offerPrice`.

2018-02-05 09:15 UTC, ipetropolsky commented on homework/task4.xsl
> +			<p class="card-text" style="max-height: 6em; overflow:hidden;"><xsl:value-of select="description" /></p>
Длинные элементы для читабельности лучше разбивать на несколько строк.

2018-02-05 09:15 UTC, ipetropolsky commented on homework/task4.xsl
> +			<xsl:apply-imports />
Опасно! Представь, что появился другой вариант `offerBody`, как сделано для `offerWrapper`. Мы подключаем его, а он выводится прямо посреди исходного шаблона вместо того чтобы заменить его.

Для таких случаев и нужны режимы, применяешь тут шаблон с `mode="badges-list"`, и всё уже гораздо прозрачнее. `apply-imports` на самом деле нужен крайне редко, он усложняет поддержку и понимание кода, так что по возможности лучше его избегать.

Ты как бы говоришь XSLT-процессору: тут будет исключение из правил, и он делает так, как обычно не делает — применяет шаблоны с более низким приоритетом импорта, которые должен был проигнорировать.

2018-02-05 09:15 UTC, ipetropolsky commented on homework/task4_badges.xsl
> +			</xsl:if>
Давай попробуем применить тут три шаблона к `offer`? Увидишь, что кода станет меньше )

2018-02-05 09:15 UTC, ipetropolsky commented on homework/task_group_by.xsl
> +	<xsl:key name="vend" match="offer" use="string(vendor)" />
Лучше явно взять `vendor/text()`, а можно и просто `vendor`, по умолчанию возьмётся `text()`.
И при использовании ключа передать то же самое.

2018-02-05 09:15 UTC, ipetropolsky commented on homework/task_group_by.xsl
> +				<xsl:copy-of select="current()"/>
`select="."`

2018-02-05 09:15 UTC, ipetropolsky commented on homework/task_offer_tree.xsl
> +				<xsl:apply-templates select="../../offers/offer[categoryId = current()/@id]" />
1) Ходить по точкам — ненадёжно и ненаглядно. Если нужен определённый родитель, лучше использовать ось `ancestor`. Но тут мы из каждой `shop/categories/category` идём в `shop/offers/offer`, то есть путь вообще никак не зависит от текущего контекста, поэтому нет смысла делать его относительным, это только мешает.
2) > Applying stylesheet took 247 ms

    Давай попробуем через ключ получать `offer`'ы, как изменится время работы? (см. `--timing` у xsltproc)

2018-02-05 09:15 UTC, ipetropolsky commented on homework/task4.xsl
> +				<xsl:value-of select="." disable-output-escaping="yes" />
Зачем дизейблить эскейпинг? Это тоже штука, которой по возможности надо избегать, потому что она легко ломает XML/HTML и открывает уязвимости.

2018-02-18 14:12 UTC, gooverdian commented on homework/task_offer_tree.xsl
> +				<xsl:apply-templates select="../../offers/offer[categoryId = current()/@id]" />
по 2. - На моем компьютере стало в 4 раза быстрее, спасибо =)

2018-03-02 11:38 UTC, ipetropolsky commented on homework/task4.xsl
> +            <xsl:apply-templates select="." mode="badgesList" />
Нужен ещё дефолтный шаблон. Если ни один из `task4_badges.xsl` не подойдёт, применятся встроенные шаблоны, и в этом месте выведется всё текстовое содержимое `offer`.

2022-04-11 10:50 UTC, closed without merging